cc_library(
    name = "greeter",
    srcs = ["src/greeter.cpp"],
    hdrs = ["include/greeter.h"],
    visibility = ["//visibility:public"],
    deps = ["@fmt"],
)

# Make the files available to doxygen
filegroup(
    name = "sources",
    srcs = glob([
        "include/*.h",
        "src/*.cpp",
    ]),
    visibility = ["//visibility:public"],
)
