load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_library", "go_binary", "go_test")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load")
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_test.bzl", "py_test")
load("@testcontainers_deps//:requirements.bzl", "requirement")

# This rule generates two targets:
#
# `bazel run requirements.update` will regenerate the requirements_txt file
#
# `bazel test requirements_test` will test that the requirements_txt file is up to date
#
compile_pip_requirements(
    name = "requirements",
    src = "requirements.in",
    requirements_txt = "requirements_lock_3_12.txt",
)

py_binary(
    name = "integration_test",
    srcs = ["integration_test.py"],
    python_version = "3.12",
    deps = [
        requirement("numpy"),
    ],
)

pkg_tar(
    name = "tar",
    srcs = [":integration_test"],
    include_runfiles = True,
)

oci_image(
    name = "image",
    base = "@distroless_python",
    entrypoint = ["/integration_test"],
    tars = [":tar"],
)

# $ bazel run integration:tarball
oci_load(
    name = "tarball",
    image = ":image",
    repo_tags = ["python-service:latest"],
)

filegroup(
    name = "tarball.tar",
    srcs = [":tarball"],
    output_group = "tarball",
)

py_test(
    name = "service_test",
    srcs = [
        "service_test.py",
    ],
    data = [
        ":tarball.tar",
    ],
    env = {"TARBALL_RUNFILE": "$(rlocationpath :tarball.tar)"},
    tags = [
        "requires-docker",
        "requires-network",
    ],
    deps = [
        requirement("docker"),
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)

# This file tells Bazel what to build.
#
# The part that loads the "gazelle" rule and declares the "gazelle" target
# are hand-written. Gazelle can be run with:
#
#     bazel run //integration:gazelle

# gazelle:prefix github.com/calmette54/BazelStarterTemplate/integration
gazelle(name = "gazelle")

go_library(
    name = "hello_lib",
    srcs = ["hello.go"],
    importpath = "github.com/calmette54/BazelStarterTemplate/integration",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "hello",
    embed = [":hello_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "hello_test",
    srcs = ["hello_test.go"],
    embed = [":hello_lib"],
)

go_library(
    name = "basic_gazelle_lib",
    srcs = ["printlinks.go"],
    importpath = "github.com/bazel-contrib/rules_go/examples/basic_gazelle",
    visibility = ["//visibility:private"],
    deps = [
        "@org_golang_x_net//html",
        "@org_golang_x_net//html/atom",
    ],
)

go_binary(
    name = "basic_gazelle",
    embed = [":basic_gazelle_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "basic_gazelle_test",
    srcs = ["printlinks_test.go"],
    embed = [":basic_gazelle_lib"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@org_golang_x_net//html",
    ],
)
