load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_test.bzl", "py_test")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")
load("@testcontainers_deps//:requirements.bzl", "requirement")

# This rule generates two targets:
#
# `bazel run requirements.update` will regenerate the requirements_txt file
#
# `bazel test requirements_test` will test that the requirements_txt file is up to date
#
compile_pip_requirements(
    name = "requirements",
    src = "requirements.in",
    requirements_txt = "requirements_lock_3_12.txt",
)

py_binary(
    name = "integration_test",
    srcs = ["integration_test.py"],
    python_version="3.12",
    deps = [
        requirement("numpy"),
    ],
)

load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "tar",
    srcs = [":integration_test"],
    include_runfiles = True,
)

oci_image(
    name = "image",
    base = "@distroless_python",
    entrypoint = ["/integration_test"],
    tars = [":tar"],
)

# $ bazel run integration:tarball
oci_load(
    name = "tarball",
    image = ":image",
    repo_tags = ["python-service:latest"],
)

filegroup(
    name = "tarball.tar",
    srcs = [":tarball"],
    output_group = "tarball",
)

py_test(
    name = "service_test",
    srcs = [
        "service_test.py",
    ],
    data = [
        ":tarball.tar",
    ],
    env = {"TARBALL_RUNFILE": "$(rlocationpath :tarball.tar)"},
    tags = [
        "requires-docker",
        "requires-network",
    ],
    deps = [
        requirement("docker"),
        requirement("pytest"),
        requirement("testcontainers"),
    ],
)

load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "hello_lib",
    srcs = ["hello.go"],
    importpath = "github.com/bazel-contrib/rules_go/examples/hello",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "hello",
    embed = [":hello_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "hello_test",
    srcs = ["hello_test.go"],
    embed = [":hello_lib"],
)
# load("@rules_go//go:def.bzl", "go_test")
#
# go_test(
#     name = "integration_test_go",
#     srcs = ["integration_test.go"],
# )
